### ISSUE TITLE
Two route docs. rendering issues in "Parameters" section

### ISSUE THREAD

**Issue by cubroe** [DIYgod/RSSHub#14875]
### Routes

```routes
/freecomputerbooks/:category?
```

### Full routes

```fullroutes
/freecomputerbooks/
```

### Related documentation

https://docs.rsshub.app/routes/reading#free-computer-books

### What is expected?

The **Parameters** section should render the parameter description as—
> `category`, optional - A category id., which should be the HTML file name (but **without** the `.html` suffix) in the URL path of a book list page.

### What is actually happening?

But it does this way—
> `category`, required - A category id., which should be the HTML file name (but \<strong>without\</strong> the \<code>.html\</code> suffix) in the URL path of a book list page.

Notice that—
1. The parameter's optionality fails to be identified/respected.
2. The Markdown elements do get converted into HTML tags but the latter get further escaped from HTML rendering.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
The issue is not exclusive to the mentioned route. I've simply searched the word "required" to find no relevant issues so far. This seems to be a new behavior change during the current rework of the whole codebase underway, as I remember the v2 routes' docs. used to be rendered normal.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Fixed in https://github.com/RSSNext/rsshub-docs/pull/11

**Comment by cubroe** [comment]
@TonyRL The optionality recognition seems still broken, e.g., for https://docs.rsshub.app/routes/reading#free-computer-books

| Expected | Actual |
| :----: | :----: |
| `category`, optional - ... | `category`, required -  |
